// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.20.3
// source: dicer.proto

package dicerproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SliceletDataP_State int32

const (
	SliceletDataP_UNKNOWN     SliceletDataP_State = 0
	SliceletDataP_NOT_READY   SliceletDataP_State = 1
	SliceletDataP_RUNNING     SliceletDataP_State = 2
	SliceletDataP_TERMINATING SliceletDataP_State = 3
)

// Enum value maps for SliceletDataP_State.
var (
	SliceletDataP_State_name = map[int32]string{
		0: "UNKNOWN",
		1: "NOT_READY",
		2: "RUNNING",
		3: "TERMINATING",
	}
	SliceletDataP_State_value = map[string]int32{
		"UNKNOWN":     0,
		"NOT_READY":   1,
		"RUNNING":     2,
		"TERMINATING": 3,
	}
)

func (x SliceletDataP_State) Enum() *SliceletDataP_State {
	p := new(SliceletDataP_State)
	*p = x
	return p
}

func (x SliceletDataP_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SliceletDataP_State) Descriptor() protoreflect.EnumDescriptor {
	return file_dicer_proto_enumTypes[0].Descriptor()
}

func (SliceletDataP_State) Type() protoreflect.EnumType {
	return &file_dicer_proto_enumTypes[0]
}

func (x SliceletDataP_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SliceletDataP_State.Descriptor instead.
func (SliceletDataP_State) EnumDescriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{12, 0}
}

// Range of keys in Dicer: [low_inclusive, high_exclusive).
// If high_exclusive is not set or empty and is_high_infinity is true, it represents +Infinity.
type SliceP struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	LowInclusive   []byte                 `protobuf:"bytes,1,opt,name=low_inclusive,json=lowInclusive,proto3" json:"low_inclusive,omitempty"`
	HighExclusive  []byte                 `protobuf:"bytes,2,opt,name=high_exclusive,json=highExclusive,proto3,oneof" json:"high_exclusive,omitempty"`
	IsHighInfinity bool                   `protobuf:"varint,3,opt,name=is_high_infinity,json=isHighInfinity,proto3" json:"is_high_infinity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SliceP) Reset() {
	*x = SliceP{}
	mi := &file_dicer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceP) ProtoMessage() {}

func (x *SliceP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceP.ProtoReflect.Descriptor instead.
func (*SliceP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{0}
}

func (x *SliceP) GetLowInclusive() []byte {
	if x != nil {
		return x.LowInclusive
	}
	return nil
}

func (x *SliceP) GetHighExclusive() []byte {
	if x != nil {
		return x.HighExclusive
	}
	return nil
}

func (x *SliceP) GetIsHighInfinity() bool {
	if x != nil {
		return x.IsHighInfinity
	}
	return false
}

// Globally unique identifier for a Slicelet incarnation (SQUID).
type SquidP struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ResourceAddress    string                 `protobuf:"bytes,1,opt,name=resource_address,json=resourceAddress,proto3" json:"resource_address,omitempty"`
	CreationTimeMillis int64                  `protobuf:"varint,2,opt,name=creation_time_millis,json=creationTimeMillis,proto3" json:"creation_time_millis,omitempty"`
	ResourceUuidHigh   int64                  `protobuf:"varint,3,opt,name=resource_uuid_high,json=resourceUuidHigh,proto3" json:"resource_uuid_high,omitempty"`
	ResourceUuidLow    int64                  `protobuf:"varint,4,opt,name=resource_uuid_low,json=resourceUuidLow,proto3" json:"resource_uuid_low,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SquidP) Reset() {
	*x = SquidP{}
	mi := &file_dicer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SquidP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquidP) ProtoMessage() {}

func (x *SquidP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquidP.ProtoReflect.Descriptor instead.
func (*SquidP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{1}
}

func (x *SquidP) GetResourceAddress() string {
	if x != nil {
		return x.ResourceAddress
	}
	return ""
}

func (x *SquidP) GetCreationTimeMillis() int64 {
	if x != nil {
		return x.CreationTimeMillis
	}
	return 0
}

func (x *SquidP) GetResourceUuidHigh() int64 {
	if x != nil {
		return x.ResourceUuidHigh
	}
	return 0
}

func (x *SquidP) GetResourceUuidLow() int64 {
	if x != nil {
		return x.ResourceUuidLow
	}
	return 0
}

// 128-bit Generation version for assignments.
type GenerationP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Incarnation   int64                  `protobuf:"varint,1,opt,name=incarnation,proto3" json:"incarnation,omitempty"`
	Number        int64                  `protobuf:"varint,2,opt,name=number,proto3" json:"number,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerationP) Reset() {
	*x = GenerationP{}
	mi := &file_dicer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerationP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerationP) ProtoMessage() {}

func (x *GenerationP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerationP.ProtoReflect.Descriptor instead.
func (*GenerationP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{2}
}

func (x *GenerationP) GetIncarnation() int64 {
	if x != nil {
		return x.Incarnation
	}
	return 0
}

func (x *GenerationP) GetNumber() int64 {
	if x != nil {
		return x.Number
	}
	return 0
}

// Request to transfer a subslice assignment between resources.
type TransferP struct {
	state                               protoimpl.MessageState `protogen:"open.v1"`
	Id                                  int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	FromResourceId                      int32                  `protobuf:"varint,2,opt,name=from_resource_id,json=fromResourceId,proto3" json:"from_resource_id,omitempty"`
	ContinuousOwnershipGenerationNumber *int64                 `protobuf:"varint,3,opt,name=continuous_ownership_generation_number,json=continuousOwnershipGenerationNumber,proto3,oneof" json:"continuous_ownership_generation_number,omitempty"`
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *TransferP) Reset() {
	*x = TransferP{}
	mi := &file_dicer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferP) ProtoMessage() {}

func (x *TransferP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferP.ProtoReflect.Descriptor instead.
func (*TransferP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{3}
}

func (x *TransferP) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TransferP) GetFromResourceId() int32 {
	if x != nil {
		return x.FromResourceId
	}
	return 0
}

func (x *TransferP) GetContinuousOwnershipGenerationNumber() int64 {
	if x != nil && x.ContinuousOwnershipGenerationNumber != nil {
		return *x.ContinuousOwnershipGenerationNumber
	}
	return 0
}

// Annotation about a subslice continuously assigned to a resource.
type SubsliceAnnotationP struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ResourceId       int32                  `protobuf:"varint,1,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	Subslice         *SliceP                `protobuf:"bytes,2,opt,name=subslice,proto3" json:"subslice,omitempty"`
	GenerationNumber int64                  `protobuf:"varint,3,opt,name=generation_number,json=generationNumber,proto3" json:"generation_number,omitempty"`
	StateTransfer    *TransferP             `protobuf:"bytes,4,opt,name=state_transfer,json=stateTransfer,proto3,oneof" json:"state_transfer,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SubsliceAnnotationP) Reset() {
	*x = SubsliceAnnotationP{}
	mi := &file_dicer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubsliceAnnotationP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubsliceAnnotationP) ProtoMessage() {}

func (x *SubsliceAnnotationP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubsliceAnnotationP.ProtoReflect.Descriptor instead.
func (*SubsliceAnnotationP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{4}
}

func (x *SubsliceAnnotationP) GetResourceId() int32 {
	if x != nil {
		return x.ResourceId
	}
	return 0
}

func (x *SubsliceAnnotationP) GetSubslice() *SliceP {
	if x != nil {
		return x.Subslice
	}
	return nil
}

func (x *SubsliceAnnotationP) GetGenerationNumber() int64 {
	if x != nil {
		return x.GenerationNumber
	}
	return 0
}

func (x *SubsliceAnnotationP) GetStateTransfer() *TransferP {
	if x != nil {
		return x.StateTransfer
	}
	return nil
}

// Assignment of a Slice to one or more resources.
type SliceAssignmentP struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Slice               *SliceP                `protobuf:"bytes,1,opt,name=slice,proto3" json:"slice,omitempty"`
	Generation          *GenerationP           `protobuf:"bytes,2,opt,name=generation,proto3" json:"generation,omitempty"`
	ResourceIndices     []int32                `protobuf:"varint,3,rep,packed,name=resource_indices,json=resourceIndices,proto3" json:"resource_indices,omitempty"`
	SubsliceAnnotations []*SubsliceAnnotationP `protobuf:"bytes,4,rep,name=subslice_annotations,json=subsliceAnnotations,proto3" json:"subslice_annotations,omitempty"`
	PrimaryRateLoad     *float64               `protobuf:"fixed64,5,opt,name=primary_rate_load,json=primaryRateLoad,proto3,oneof" json:"primary_rate_load,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SliceAssignmentP) Reset() {
	*x = SliceAssignmentP{}
	mi := &file_dicer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceAssignmentP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceAssignmentP) ProtoMessage() {}

func (x *SliceAssignmentP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceAssignmentP.ProtoReflect.Descriptor instead.
func (*SliceAssignmentP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{5}
}

func (x *SliceAssignmentP) GetSlice() *SliceP {
	if x != nil {
		return x.Slice
	}
	return nil
}

func (x *SliceAssignmentP) GetGeneration() *GenerationP {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *SliceAssignmentP) GetResourceIndices() []int32 {
	if x != nil {
		return x.ResourceIndices
	}
	return nil
}

func (x *SliceAssignmentP) GetSubsliceAnnotations() []*SubsliceAnnotationP {
	if x != nil {
		return x.SubsliceAnnotations
	}
	return nil
}

func (x *SliceAssignmentP) GetPrimaryRateLoad() float64 {
	if x != nil && x.PrimaryRateLoad != nil {
		return *x.PrimaryRateLoad
	}
	return 0
}

// Full or diff assignment.
type DiffAssignmentP struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Generation       *GenerationP           `protobuf:"bytes,1,opt,name=generation,proto3" json:"generation,omitempty"`
	SliceAssignments []*SliceAssignmentP    `protobuf:"bytes,2,rep,name=slice_assignments,json=sliceAssignments,proto3" json:"slice_assignments,omitempty"`
	Resources        []*SquidP              `protobuf:"bytes,3,rep,name=resources,proto3" json:"resources,omitempty"`
	IsFrozen         bool                   `protobuf:"varint,4,opt,name=is_frozen,json=isFrozen,proto3" json:"is_frozen,omitempty"`
	DiffGeneration   *GenerationP           `protobuf:"bytes,5,opt,name=diff_generation,json=diffGeneration,proto3,oneof" json:"diff_generation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DiffAssignmentP) Reset() {
	*x = DiffAssignmentP{}
	mi := &file_dicer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DiffAssignmentP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffAssignmentP) ProtoMessage() {}

func (x *DiffAssignmentP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffAssignmentP.ProtoReflect.Descriptor instead.
func (*DiffAssignmentP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{6}
}

func (x *DiffAssignmentP) GetGeneration() *GenerationP {
	if x != nil {
		return x.Generation
	}
	return nil
}

func (x *DiffAssignmentP) GetSliceAssignments() []*SliceAssignmentP {
	if x != nil {
		return x.SliceAssignments
	}
	return nil
}

func (x *DiffAssignmentP) GetResources() []*SquidP {
	if x != nil {
		return x.Resources
	}
	return nil
}

func (x *DiffAssignmentP) GetIsFrozen() bool {
	if x != nil {
		return x.IsFrozen
	}
	return false
}

func (x *DiffAssignmentP) GetDiffGeneration() *GenerationP {
	if x != nil {
		return x.DiffGeneration
	}
	return nil
}

// Sync assignment state between client/server and assigner.
type SyncAssignmentStateP struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to State:
	//
	//	*SyncAssignmentStateP_KnownGeneration
	//	*SyncAssignmentStateP_KnownAssignment
	//	*SyncAssignmentStateP_KnownSerializedAssignment
	State         isSyncAssignmentStateP_State `protobuf_oneof:"state"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAssignmentStateP) Reset() {
	*x = SyncAssignmentStateP{}
	mi := &file_dicer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAssignmentStateP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAssignmentStateP) ProtoMessage() {}

func (x *SyncAssignmentStateP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAssignmentStateP.ProtoReflect.Descriptor instead.
func (*SyncAssignmentStateP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{7}
}

func (x *SyncAssignmentStateP) GetState() isSyncAssignmentStateP_State {
	if x != nil {
		return x.State
	}
	return nil
}

func (x *SyncAssignmentStateP) GetKnownGeneration() *GenerationP {
	if x != nil {
		if x, ok := x.State.(*SyncAssignmentStateP_KnownGeneration); ok {
			return x.KnownGeneration
		}
	}
	return nil
}

func (x *SyncAssignmentStateP) GetKnownAssignment() *DiffAssignmentP {
	if x != nil {
		if x, ok := x.State.(*SyncAssignmentStateP_KnownAssignment); ok {
			return x.KnownAssignment
		}
	}
	return nil
}

func (x *SyncAssignmentStateP) GetKnownSerializedAssignment() []byte {
	if x != nil {
		if x, ok := x.State.(*SyncAssignmentStateP_KnownSerializedAssignment); ok {
			return x.KnownSerializedAssignment
		}
	}
	return nil
}

type isSyncAssignmentStateP_State interface {
	isSyncAssignmentStateP_State()
}

type SyncAssignmentStateP_KnownGeneration struct {
	KnownGeneration *GenerationP `protobuf:"bytes,1,opt,name=known_generation,json=knownGeneration,proto3,oneof"`
}

type SyncAssignmentStateP_KnownAssignment struct {
	KnownAssignment *DiffAssignmentP `protobuf:"bytes,2,opt,name=known_assignment,json=knownAssignment,proto3,oneof"`
}

type SyncAssignmentStateP_KnownSerializedAssignment struct {
	KnownSerializedAssignment []byte `protobuf:"bytes,3,opt,name=known_serialized_assignment,json=knownSerializedAssignment,proto3,oneof"`
}

func (*SyncAssignmentStateP_KnownGeneration) isSyncAssignmentStateP_State() {}

func (*SyncAssignmentStateP_KnownAssignment) isSyncAssignmentStateP_State() {}

func (*SyncAssignmentStateP_KnownSerializedAssignment) isSyncAssignmentStateP_State() {}

// Instruction for redirecting client requests.
type RedirectP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	RedirectToken []byte                 `protobuf:"bytes,2,opt,name=redirect_token,json=redirectToken,proto3" json:"redirect_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedirectP) Reset() {
	*x = RedirectP{}
	mi := &file_dicer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedirectP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedirectP) ProtoMessage() {}

func (x *RedirectP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedirectP.ProtoReflect.Descriptor instead.
func (*RedirectP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{8}
}

func (x *RedirectP) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RedirectP) GetRedirectToken() []byte {
	if x != nil {
		return x.RedirectToken
	}
	return nil
}

// Logical target descriptor for a sharded service.
type TargetP struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	KubernetesClusterUri string                 `protobuf:"bytes,2,opt,name=kubernetes_cluster_uri,json=kubernetesClusterUri,proto3" json:"kubernetes_cluster_uri,omitempty"`
	InstanceId           string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *TargetP) Reset() {
	*x = TargetP{}
	mi := &file_dicer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TargetP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TargetP) ProtoMessage() {}

func (x *TargetP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TargetP.ProtoReflect.Descriptor instead.
func (*TargetP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{9}
}

func (x *TargetP) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TargetP) GetKubernetesClusterUri() string {
	if x != nil {
		return x.KubernetesClusterUri
	}
	return ""
}

func (x *TargetP) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

// Key-level load estimate.
type KeyLoadP struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	SliceKey                      []byte                 `protobuf:"bytes,1,opt,name=slice_key,json=sliceKey,proto3" json:"slice_key,omitempty"`
	UnderestimatedPrimaryRateLoad float64                `protobuf:"fixed64,2,opt,name=underestimated_primary_rate_load,json=underestimatedPrimaryRateLoad,proto3" json:"underestimated_primary_rate_load,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *KeyLoadP) Reset() {
	*x = KeyLoadP{}
	mi := &file_dicer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyLoadP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyLoadP) ProtoMessage() {}

func (x *KeyLoadP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyLoadP.ProtoReflect.Descriptor instead.
func (*KeyLoadP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{10}
}

func (x *KeyLoadP) GetSliceKey() []byte {
	if x != nil {
		return x.SliceKey
	}
	return nil
}

func (x *KeyLoadP) GetUnderestimatedPrimaryRateLoad() float64 {
	if x != nil {
		return x.UnderestimatedPrimaryRateLoad
	}
	return 0
}

// Aggregate load measurements on a Slice replica.
type SliceLoadP struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	PrimaryRateLoad            float64                `protobuf:"fixed64,1,opt,name=primary_rate_load,json=primaryRateLoad,proto3" json:"primary_rate_load,omitempty"`
	WindowLowInclusiveSeconds  int64                  `protobuf:"varint,2,opt,name=window_low_inclusive_seconds,json=windowLowInclusiveSeconds,proto3" json:"window_low_inclusive_seconds,omitempty"`
	WindowHighExclusiveSeconds int64                  `protobuf:"varint,3,opt,name=window_high_exclusive_seconds,json=windowHighExclusiveSeconds,proto3" json:"window_high_exclusive_seconds,omitempty"`
	Slice                      *SliceP                `protobuf:"bytes,4,opt,name=slice,proto3" json:"slice,omitempty"`
	TopKeys                    []*KeyLoadP            `protobuf:"bytes,5,rep,name=top_keys,json=topKeys,proto3" json:"top_keys,omitempty"`
	NumReplicas                int32                  `protobuf:"varint,6,opt,name=num_replicas,json=numReplicas,proto3" json:"num_replicas,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *SliceLoadP) Reset() {
	*x = SliceLoadP{}
	mi := &file_dicer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceLoadP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceLoadP) ProtoMessage() {}

func (x *SliceLoadP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceLoadP.ProtoReflect.Descriptor instead.
func (*SliceLoadP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{11}
}

func (x *SliceLoadP) GetPrimaryRateLoad() float64 {
	if x != nil {
		return x.PrimaryRateLoad
	}
	return 0
}

func (x *SliceLoadP) GetWindowLowInclusiveSeconds() int64 {
	if x != nil {
		return x.WindowLowInclusiveSeconds
	}
	return 0
}

func (x *SliceLoadP) GetWindowHighExclusiveSeconds() int64 {
	if x != nil {
		return x.WindowHighExclusiveSeconds
	}
	return 0
}

func (x *SliceLoadP) GetSlice() *SliceP {
	if x != nil {
		return x.Slice
	}
	return nil
}

func (x *SliceLoadP) GetTopKeys() []*KeyLoadP {
	if x != nil {
		return x.TopKeys
	}
	return nil
}

func (x *SliceLoadP) GetNumReplicas() int32 {
	if x != nil {
		return x.NumReplicas
	}
	return 0
}

// Health and state reported by a Slicelet.
type SliceletDataP struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Squid                   *SquidP                `protobuf:"bytes,1,opt,name=squid,proto3" json:"squid,omitempty"`
	State                   SliceletDataP_State    `protobuf:"varint,2,opt,name=state,proto3,enum=dicer.SliceletDataP_State" json:"state,omitempty"`
	AttributedLoads         []*SliceLoadP          `protobuf:"bytes,3,rep,name=attributed_loads,json=attributedLoads,proto3" json:"attributed_loads,omitempty"`
	UnattributedLoad        *SliceLoadP            `protobuf:"bytes,4,opt,name=unattributed_load,json=unattributedLoad,proto3,oneof" json:"unattributed_load,omitempty"`
	NeverRecalledGeneration *GenerationP           `protobuf:"bytes,5,opt,name=never_recalled_generation,json=neverRecalledGeneration,proto3,oneof" json:"never_recalled_generation,omitempty"`
	ReleasedSquids          []*SquidP              `protobuf:"bytes,6,rep,name=released_squids,json=releasedSquids,proto3" json:"released_squids,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *SliceletDataP) Reset() {
	*x = SliceletDataP{}
	mi := &file_dicer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SliceletDataP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SliceletDataP) ProtoMessage() {}

func (x *SliceletDataP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SliceletDataP.ProtoReflect.Descriptor instead.
func (*SliceletDataP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{12}
}

func (x *SliceletDataP) GetSquid() *SquidP {
	if x != nil {
		return x.Squid
	}
	return nil
}

func (x *SliceletDataP) GetState() SliceletDataP_State {
	if x != nil {
		return x.State
	}
	return SliceletDataP_UNKNOWN
}

func (x *SliceletDataP) GetAttributedLoads() []*SliceLoadP {
	if x != nil {
		return x.AttributedLoads
	}
	return nil
}

func (x *SliceletDataP) GetUnattributedLoad() *SliceLoadP {
	if x != nil {
		return x.UnattributedLoad
	}
	return nil
}

func (x *SliceletDataP) GetNeverRecalledGeneration() *GenerationP {
	if x != nil {
		return x.NeverRecalledGeneration
	}
	return nil
}

func (x *SliceletDataP) GetReleasedSquids() []*SquidP {
	if x != nil {
		return x.ReleasedSquids
	}
	return nil
}

// Clerk-specific telemetry or debug fields.
type ClerkDataP struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClientId      string                 `protobuf:"bytes,1,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClerkDataP) Reset() {
	*x = ClerkDataP{}
	mi := &file_dicer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClerkDataP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClerkDataP) ProtoMessage() {}

func (x *ClerkDataP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClerkDataP.ProtoReflect.Descriptor instead.
func (*ClerkDataP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{13}
}

func (x *ClerkDataP) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

// Watch request sent by Clerk or Slicelet.
type ClientRequestP struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Target                 *TargetP               `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	SyncAssignmentState    *SyncAssignmentStateP  `protobuf:"bytes,2,opt,name=sync_assignment_state,json=syncAssignmentState,proto3" json:"sync_assignment_state,omitempty"`
	SubscriberDebugName    string                 `protobuf:"bytes,3,opt,name=subscriber_debug_name,json=subscriberDebugName,proto3" json:"subscriber_debug_name,omitempty"`
	ChosenRpcTimeoutMillis int64                  `protobuf:"varint,4,opt,name=chosen_rpc_timeout_millis,json=chosenRpcTimeoutMillis,proto3" json:"chosen_rpc_timeout_millis,omitempty"`
	// Types that are valid to be assigned to SubscriberData:
	//
	//	*ClientRequestP_ClerkFields
	//	*ClientRequestP_SliceletFields
	SubscriberData isClientRequestP_SubscriberData `protobuf_oneof:"subscriber_data"`
	Version        int64                           `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	RedirectToken  []byte                          `protobuf:"bytes,8,opt,name=redirect_token,json=redirectToken,proto3" json:"redirect_token,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ClientRequestP) Reset() {
	*x = ClientRequestP{}
	mi := &file_dicer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientRequestP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientRequestP) ProtoMessage() {}

func (x *ClientRequestP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientRequestP.ProtoReflect.Descriptor instead.
func (*ClientRequestP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{14}
}

func (x *ClientRequestP) GetTarget() *TargetP {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *ClientRequestP) GetSyncAssignmentState() *SyncAssignmentStateP {
	if x != nil {
		return x.SyncAssignmentState
	}
	return nil
}

func (x *ClientRequestP) GetSubscriberDebugName() string {
	if x != nil {
		return x.SubscriberDebugName
	}
	return ""
}

func (x *ClientRequestP) GetChosenRpcTimeoutMillis() int64 {
	if x != nil {
		return x.ChosenRpcTimeoutMillis
	}
	return 0
}

func (x *ClientRequestP) GetSubscriberData() isClientRequestP_SubscriberData {
	if x != nil {
		return x.SubscriberData
	}
	return nil
}

func (x *ClientRequestP) GetClerkFields() *ClerkDataP {
	if x != nil {
		if x, ok := x.SubscriberData.(*ClientRequestP_ClerkFields); ok {
			return x.ClerkFields
		}
	}
	return nil
}

func (x *ClientRequestP) GetSliceletFields() *SliceletDataP {
	if x != nil {
		if x, ok := x.SubscriberData.(*ClientRequestP_SliceletFields); ok {
			return x.SliceletFields
		}
	}
	return nil
}

func (x *ClientRequestP) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ClientRequestP) GetRedirectToken() []byte {
	if x != nil {
		return x.RedirectToken
	}
	return nil
}

type isClientRequestP_SubscriberData interface {
	isClientRequestP_SubscriberData()
}

type ClientRequestP_ClerkFields struct {
	ClerkFields *ClerkDataP `protobuf:"bytes,5,opt,name=clerk_fields,json=clerkFields,proto3,oneof"`
}

type ClientRequestP_SliceletFields struct {
	SliceletFields *SliceletDataP `protobuf:"bytes,6,opt,name=slicelet_fields,json=sliceletFields,proto3,oneof"`
}

func (*ClientRequestP_ClerkFields) isClientRequestP_SubscriberData() {}

func (*ClientRequestP_SliceletFields) isClientRequestP_SubscriberData() {}

// Watch response returned by Assigner.
type ClientResponseP struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	SyncAssignmentState       *SyncAssignmentStateP  `protobuf:"bytes,1,opt,name=sync_assignment_state,json=syncAssignmentState,proto3" json:"sync_assignment_state,omitempty"`
	SuggestedRpcTimeoutMillis int64                  `protobuf:"varint,2,opt,name=suggested_rpc_timeout_millis,json=suggestedRpcTimeoutMillis,proto3" json:"suggested_rpc_timeout_millis,omitempty"`
	Redirect                  *RedirectP             `protobuf:"bytes,3,opt,name=redirect,proto3" json:"redirect,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ClientResponseP) Reset() {
	*x = ClientResponseP{}
	mi := &file_dicer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponseP) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponseP) ProtoMessage() {}

func (x *ClientResponseP) ProtoReflect() protoreflect.Message {
	mi := &file_dicer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponseP.ProtoReflect.Descriptor instead.
func (*ClientResponseP) Descriptor() ([]byte, []int) {
	return file_dicer_proto_rawDescGZIP(), []int{15}
}

func (x *ClientResponseP) GetSyncAssignmentState() *SyncAssignmentStateP {
	if x != nil {
		return x.SyncAssignmentState
	}
	return nil
}

func (x *ClientResponseP) GetSuggestedRpcTimeoutMillis() int64 {
	if x != nil {
		return x.SuggestedRpcTimeoutMillis
	}
	return 0
}

func (x *ClientResponseP) GetRedirect() *RedirectP {
	if x != nil {
		return x.Redirect
	}
	return nil
}

var File_dicer_proto protoreflect.FileDescriptor

const file_dicer_proto_rawDesc = "" +
	"\n" +
	"\vdicer.proto\x12\x05dicer\"\x96\x01\n" +
	"\x06SliceP\x12#\n" +
	"\rlow_inclusive\x18\x01 \x01(\fR\flowInclusive\x12*\n" +
	"\x0ehigh_exclusive\x18\x02 \x01(\fH\x00R\rhighExclusive\x88\x01\x01\x12(\n" +
	"\x10is_high_infinity\x18\x03 \x01(\bR\x0eisHighInfinityB\x11\n" +
	"\x0f_high_exclusive\"\xbf\x01\n" +
	"\x06SquidP\x12)\n" +
	"\x10resource_address\x18\x01 \x01(\tR\x0fresourceAddress\x120\n" +
	"\x14creation_time_millis\x18\x02 \x01(\x03R\x12creationTimeMillis\x12,\n" +
	"\x12resource_uuid_high\x18\x03 \x01(\x03R\x10resourceUuidHigh\x12*\n" +
	"\x11resource_uuid_low\x18\x04 \x01(\x03R\x0fresourceUuidLow\"G\n" +
	"\vGenerationP\x12 \n" +
	"\vincarnation\x18\x01 \x01(\x03R\vincarnation\x12\x16\n" +
	"\x06number\x18\x02 \x01(\x03R\x06number\"\xca\x01\n" +
	"\tTransferP\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12(\n" +
	"\x10from_resource_id\x18\x02 \x01(\x05R\x0efromResourceId\x12X\n" +
	"&continuous_ownership_generation_number\x18\x03 \x01(\x03H\x00R#continuousOwnershipGenerationNumber\x88\x01\x01B)\n" +
	"'_continuous_ownership_generation_number\"\xdf\x01\n" +
	"\x13SubsliceAnnotationP\x12\x1f\n" +
	"\vresource_id\x18\x01 \x01(\x05R\n" +
	"resourceId\x12)\n" +
	"\bsubslice\x18\x02 \x01(\v2\r.dicer.SlicePR\bsubslice\x12+\n" +
	"\x11generation_number\x18\x03 \x01(\x03R\x10generationNumber\x12<\n" +
	"\x0estate_transfer\x18\x04 \x01(\v2\x10.dicer.TransferPH\x00R\rstateTransfer\x88\x01\x01B\x11\n" +
	"\x0f_state_transfer\"\xac\x02\n" +
	"\x10SliceAssignmentP\x12#\n" +
	"\x05slice\x18\x01 \x01(\v2\r.dicer.SlicePR\x05slice\x122\n" +
	"\n" +
	"generation\x18\x02 \x01(\v2\x12.dicer.GenerationPR\n" +
	"generation\x12)\n" +
	"\x10resource_indices\x18\x03 \x03(\x05R\x0fresourceIndices\x12M\n" +
	"\x14subslice_annotations\x18\x04 \x03(\v2\x1a.dicer.SubsliceAnnotationPR\x13subsliceAnnotations\x12/\n" +
	"\x11primary_rate_load\x18\x05 \x01(\x01H\x00R\x0fprimaryRateLoad\x88\x01\x01B\x14\n" +
	"\x12_primary_rate_load\"\xab\x02\n" +
	"\x0fDiffAssignmentP\x122\n" +
	"\n" +
	"generation\x18\x01 \x01(\v2\x12.dicer.GenerationPR\n" +
	"generation\x12D\n" +
	"\x11slice_assignments\x18\x02 \x03(\v2\x17.dicer.SliceAssignmentPR\x10sliceAssignments\x12+\n" +
	"\tresources\x18\x03 \x03(\v2\r.dicer.SquidPR\tresources\x12\x1b\n" +
	"\tis_frozen\x18\x04 \x01(\bR\bisFrozen\x12@\n" +
	"\x0fdiff_generation\x18\x05 \x01(\v2\x12.dicer.GenerationPH\x00R\x0ediffGeneration\x88\x01\x01B\x12\n" +
	"\x10_diff_generation\"\xe7\x01\n" +
	"\x14SyncAssignmentStateP\x12?\n" +
	"\x10known_generation\x18\x01 \x01(\v2\x12.dicer.GenerationPH\x00R\x0fknownGeneration\x12C\n" +
	"\x10known_assignment\x18\x02 \x01(\v2\x16.dicer.DiffAssignmentPH\x00R\x0fknownAssignment\x12@\n" +
	"\x1bknown_serialized_assignment\x18\x03 \x01(\fH\x00R\x19knownSerializedAssignmentB\a\n" +
	"\x05state\"L\n" +
	"\tRedirectP\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12%\n" +
	"\x0eredirect_token\x18\x02 \x01(\fR\rredirectToken\"t\n" +
	"\aTargetP\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x124\n" +
	"\x16kubernetes_cluster_uri\x18\x02 \x01(\tR\x14kubernetesClusterUri\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\"p\n" +
	"\bKeyLoadP\x12\x1b\n" +
	"\tslice_key\x18\x01 \x01(\fR\bsliceKey\x12G\n" +
	" underestimated_primary_rate_load\x18\x02 \x01(\x01R\x1dunderestimatedPrimaryRateLoad\"\xb0\x02\n" +
	"\n" +
	"SliceLoadP\x12*\n" +
	"\x11primary_rate_load\x18\x01 \x01(\x01R\x0fprimaryRateLoad\x12?\n" +
	"\x1cwindow_low_inclusive_seconds\x18\x02 \x01(\x03R\x19windowLowInclusiveSeconds\x12A\n" +
	"\x1dwindow_high_exclusive_seconds\x18\x03 \x01(\x03R\x1awindowHighExclusiveSeconds\x12#\n" +
	"\x05slice\x18\x04 \x01(\v2\r.dicer.SlicePR\x05slice\x12*\n" +
	"\btop_keys\x18\x05 \x03(\v2\x0f.dicer.KeyLoadPR\atopKeys\x12!\n" +
	"\fnum_replicas\x18\x06 \x01(\x05R\vnumReplicas\"\xed\x03\n" +
	"\rSliceletDataP\x12#\n" +
	"\x05squid\x18\x01 \x01(\v2\r.dicer.SquidPR\x05squid\x120\n" +
	"\x05state\x18\x02 \x01(\x0e2\x1a.dicer.SliceletDataP.StateR\x05state\x12<\n" +
	"\x10attributed_loads\x18\x03 \x03(\v2\x11.dicer.SliceLoadPR\x0fattributedLoads\x12C\n" +
	"\x11unattributed_load\x18\x04 \x01(\v2\x11.dicer.SliceLoadPH\x00R\x10unattributedLoad\x88\x01\x01\x12S\n" +
	"\x19never_recalled_generation\x18\x05 \x01(\v2\x12.dicer.GenerationPH\x01R\x17neverRecalledGeneration\x88\x01\x01\x126\n" +
	"\x0freleased_squids\x18\x06 \x03(\v2\r.dicer.SquidPR\x0ereleasedSquids\"A\n" +
	"\x05State\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\r\n" +
	"\tNOT_READY\x10\x01\x12\v\n" +
	"\aRUNNING\x10\x02\x12\x0f\n" +
	"\vTERMINATING\x10\x03B\x14\n" +
	"\x12_unattributed_loadB\x1c\n" +
	"\x1a_never_recalled_generation\")\n" +
	"\n" +
	"ClerkDataP\x12\x1b\n" +
	"\tclient_id\x18\x01 \x01(\tR\bclientId\"\xc5\x03\n" +
	"\x0eClientRequestP\x12&\n" +
	"\x06target\x18\x01 \x01(\v2\x0e.dicer.TargetPR\x06target\x12O\n" +
	"\x15sync_assignment_state\x18\x02 \x01(\v2\x1b.dicer.SyncAssignmentStatePR\x13syncAssignmentState\x122\n" +
	"\x15subscriber_debug_name\x18\x03 \x01(\tR\x13subscriberDebugName\x129\n" +
	"\x19chosen_rpc_timeout_millis\x18\x04 \x01(\x03R\x16chosenRpcTimeoutMillis\x126\n" +
	"\fclerk_fields\x18\x05 \x01(\v2\x11.dicer.ClerkDataPH\x00R\vclerkFields\x12?\n" +
	"\x0fslicelet_fields\x18\x06 \x01(\v2\x14.dicer.SliceletDataPH\x00R\x0esliceletFields\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12%\n" +
	"\x0eredirect_token\x18\b \x01(\fR\rredirectTokenB\x11\n" +
	"\x0fsubscriber_data\"\xd1\x01\n" +
	"\x0fClientResponseP\x12O\n" +
	"\x15sync_assignment_state\x18\x01 \x01(\v2\x1b.dicer.SyncAssignmentStatePR\x13syncAssignmentState\x12?\n" +
	"\x1csuggested_rpc_timeout_millis\x18\x02 \x01(\x03R\x19suggestedRpcTimeoutMillis\x12,\n" +
	"\bredirect\x18\x03 \x01(\v2\x10.dicer.RedirectPR\bredirect2K\n" +
	"\x11AssignmentService\x126\n" +
	"\x05Watch\x12\x15.dicer.ClientRequestP\x1a\x16.dicer.ClientResponsePB2Z0github.com/quangh33/godicer/pkg/proto;dicerprotob\x06proto3"

var (
	file_dicer_proto_rawDescOnce sync.Once
	file_dicer_proto_rawDescData []byte
)

func file_dicer_proto_rawDescGZIP() []byte {
	file_dicer_proto_rawDescOnce.Do(func() {
		file_dicer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_dicer_proto_rawDesc), len(file_dicer_proto_rawDesc)))
	})
	return file_dicer_proto_rawDescData
}

var file_dicer_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_dicer_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_dicer_proto_goTypes = []any{
	(SliceletDataP_State)(0),     // 0: dicer.SliceletDataP.State
	(*SliceP)(nil),               // 1: dicer.SliceP
	(*SquidP)(nil),               // 2: dicer.SquidP
	(*GenerationP)(nil),          // 3: dicer.GenerationP
	(*TransferP)(nil),            // 4: dicer.TransferP
	(*SubsliceAnnotationP)(nil),  // 5: dicer.SubsliceAnnotationP
	(*SliceAssignmentP)(nil),     // 6: dicer.SliceAssignmentP
	(*DiffAssignmentP)(nil),      // 7: dicer.DiffAssignmentP
	(*SyncAssignmentStateP)(nil), // 8: dicer.SyncAssignmentStateP
	(*RedirectP)(nil),            // 9: dicer.RedirectP
	(*TargetP)(nil),              // 10: dicer.TargetP
	(*KeyLoadP)(nil),             // 11: dicer.KeyLoadP
	(*SliceLoadP)(nil),           // 12: dicer.SliceLoadP
	(*SliceletDataP)(nil),        // 13: dicer.SliceletDataP
	(*ClerkDataP)(nil),           // 14: dicer.ClerkDataP
	(*ClientRequestP)(nil),       // 15: dicer.ClientRequestP
	(*ClientResponseP)(nil),      // 16: dicer.ClientResponseP
}
var file_dicer_proto_depIdxs = []int32{
	1,  // 0: dicer.SubsliceAnnotationP.subslice:type_name -> dicer.SliceP
	4,  // 1: dicer.SubsliceAnnotationP.state_transfer:type_name -> dicer.TransferP
	1,  // 2: dicer.SliceAssignmentP.slice:type_name -> dicer.SliceP
	3,  // 3: dicer.SliceAssignmentP.generation:type_name -> dicer.GenerationP
	5,  // 4: dicer.SliceAssignmentP.subslice_annotations:type_name -> dicer.SubsliceAnnotationP
	3,  // 5: dicer.DiffAssignmentP.generation:type_name -> dicer.GenerationP
	6,  // 6: dicer.DiffAssignmentP.slice_assignments:type_name -> dicer.SliceAssignmentP
	2,  // 7: dicer.DiffAssignmentP.resources:type_name -> dicer.SquidP
	3,  // 8: dicer.DiffAssignmentP.diff_generation:type_name -> dicer.GenerationP
	3,  // 9: dicer.SyncAssignmentStateP.known_generation:type_name -> dicer.GenerationP
	7,  // 10: dicer.SyncAssignmentStateP.known_assignment:type_name -> dicer.DiffAssignmentP
	1,  // 11: dicer.SliceLoadP.slice:type_name -> dicer.SliceP
	11, // 12: dicer.SliceLoadP.top_keys:type_name -> dicer.KeyLoadP
	2,  // 13: dicer.SliceletDataP.squid:type_name -> dicer.SquidP
	0,  // 14: dicer.SliceletDataP.state:type_name -> dicer.SliceletDataP.State
	12, // 15: dicer.SliceletDataP.attributed_loads:type_name -> dicer.SliceLoadP
	12, // 16: dicer.SliceletDataP.unattributed_load:type_name -> dicer.SliceLoadP
	3,  // 17: dicer.SliceletDataP.never_recalled_generation:type_name -> dicer.GenerationP
	2,  // 18: dicer.SliceletDataP.released_squids:type_name -> dicer.SquidP
	10, // 19: dicer.ClientRequestP.target:type_name -> dicer.TargetP
	8,  // 20: dicer.ClientRequestP.sync_assignment_state:type_name -> dicer.SyncAssignmentStateP
	14, // 21: dicer.ClientRequestP.clerk_fields:type_name -> dicer.ClerkDataP
	13, // 22: dicer.ClientRequestP.slicelet_fields:type_name -> dicer.SliceletDataP
	8,  // 23: dicer.ClientResponseP.sync_assignment_state:type_name -> dicer.SyncAssignmentStateP
	9,  // 24: dicer.ClientResponseP.redirect:type_name -> dicer.RedirectP
	15, // 25: dicer.AssignmentService.Watch:input_type -> dicer.ClientRequestP
	16, // 26: dicer.AssignmentService.Watch:output_type -> dicer.ClientResponseP
	26, // [26:27] is the sub-list for method output_type
	25, // [25:26] is the sub-list for method input_type
	25, // [25:25] is the sub-list for extension type_name
	25, // [25:25] is the sub-list for extension extendee
	0,  // [0:25] is the sub-list for field type_name
}

func init() { file_dicer_proto_init() }
func file_dicer_proto_init() {
	if File_dicer_proto != nil {
		return
	}
	file_dicer_proto_msgTypes[0].OneofWrappers = []any{}
	file_dicer_proto_msgTypes[3].OneofWrappers = []any{}
	file_dicer_proto_msgTypes[4].OneofWrappers = []any{}
	file_dicer_proto_msgTypes[5].OneofWrappers = []any{}
	file_dicer_proto_msgTypes[6].OneofWrappers = []any{}
	file_dicer_proto_msgTypes[7].OneofWrappers = []any{
		(*SyncAssignmentStateP_KnownGeneration)(nil),
		(*SyncAssignmentStateP_KnownAssignment)(nil),
		(*SyncAssignmentStateP_KnownSerializedAssignment)(nil),
	}
	file_dicer_proto_msgTypes[12].OneofWrappers = []any{}
	file_dicer_proto_msgTypes[14].OneofWrappers = []any{
		(*ClientRequestP_ClerkFields)(nil),
		(*ClientRequestP_SliceletFields)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_dicer_proto_rawDesc), len(file_dicer_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_dicer_proto_goTypes,
		DependencyIndexes: file_dicer_proto_depIdxs,
		EnumInfos:         file_dicer_proto_enumTypes,
		MessageInfos:      file_dicer_proto_msgTypes,
	}.Build()
	File_dicer_proto = out.File
	file_dicer_proto_goTypes = nil
	file_dicer_proto_depIdxs = nil
}
